name: olbase

on:
  schedule:
    - cron: '00 16 * * 2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # If on master, use the latest tag, otherwise use the branch name
      - name: Master Build and push
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/master'
        with:
          context: "."
          file: "./docker/Dockerfile.olbase"
          tags: ghcr.io/internetarchive/olbase:latest
          push: true

      # If on another branch, use the branch name -- just the branch name, not the full ref
      - name: Test Branch Build and push
        uses: docker/build-push-action@v6
        if: github.ref != 'refs/heads/master'
        with:
          context: "."
          file: "./docker/Dockerfile.olbase"
          tags: ghcr.io/internetarchive/olbase:${{ github.ref_name }}
          push: true
